// ============================================================================
// Mock Product Data
// ============================================================================
// Used when Supabase is not connected. Replace with real DB queries in production.
// ============================================================================

import type { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "prod_001",
    name: "Premium Item Alpha",
    slug: "premium-item-alpha",
    description: "High-quality product with exceptional craftsmanship. Made from the finest materials, this item represents the pinnacle of our collection. Perfect for discerning customers who demand the best.",
    category: "category-1",
    filter_field: "Option A",
    images: ["/images/products/product-1.jpg", "/images/products/product-1b.jpg"],
    retail_price: 29.99,
    wholesale_price: 19.99,
    stock_status: "IN_STOCK",
    options: ["Small", "Medium", "Large"],
    option_configs: [],
    is_archived: false,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_002",
    name: "Classic Item Beta",
    slug: "classic-item-beta",
    description: "A timeless classic that never goes out of style. Expertly designed with attention to every detail. An essential addition to any collection.",
    category: "category-1",
    filter_field: "Option B",
    images: ["/images/products/product-2.jpg"],
    retail_price: 34.99,
    wholesale_price: 24.99,
    stock_status: "IN_STOCK",
    options: ["Small", "Medium", "Large", "XL"],
    option_configs: [],
    is_archived: false,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_003",
    name: "Artisan Item Gamma",
    slug: "artisan-item-gamma",
    description: "Handcrafted with care by our artisan team. Each piece is unique, featuring subtle variations that make it truly one of a kind.",
    category: "category-2",
    filter_field: "Option A",
    images: ["/images/products/product-3.jpg"],
    retail_price: 49.99,
    wholesale_price: 34.99,
    stock_status: "IN_STOCK",
    options: ["Standard", "Premium"],
    option_configs: [],
    is_archived: false,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_004",
    name: "Deluxe Item Delta",
    slug: "deluxe-item-delta",
    description: "Our deluxe range offers unparalleled luxury. This product features premium finishing and comes in our signature packaging.",
    category: "category-2",
    filter_field: "Option C",
    images: ["/images/products/product-4.jpg"],
    retail_price: 59.99,
    wholesale_price: 42.99,
    stock_status: "LOW_STOCK",
    options: ["Small", "Medium", "Large"],
    option_configs: [],
    is_archived: false,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_005",
    name: "Essential Item Epsilon",
    slug: "essential-item-epsilon",
    description: "An everyday essential that combines practicality with style. Built to last with high-quality materials that stand the test of time.",
    category: "category-3",
    filter_field: "Option B",
    images: ["/images/products/product-5.jpg"],
    retail_price: 19.99,
    wholesale_price: 12.99,
    stock_status: "IN_STOCK",
    options: ["Standard"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_006",
    name: "Signature Item Zeta",
    slug: "signature-item-zeta",
    description: "Part of our signature collection, this item showcases our brand's commitment to quality and innovation. A perfect gift for any occasion.",
    category: "category-3",
    filter_field: "Option D",
    images: ["/images/products/product-6.jpg"],
    retail_price: 44.99,
    wholesale_price: 31.99,
    stock_status: "IN_STOCK",
    options: ["Small", "Medium", "Large"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_007",
    name: "Heritage Item Eta",
    slug: "heritage-item-eta",
    description: "Inspired by traditional methods, this product brings heritage craftsmanship into the modern era. Each batch is carefully curated.",
    category: "category-4",
    filter_field: "Option A",
    images: ["/images/products/product-7.jpg"],
    retail_price: 39.99,
    wholesale_price: 27.99,
    stock_status: "IN_STOCK",
    options: ["Standard", "Premium", "Elite"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_008",
    name: "Organic Item Theta",
    slug: "organic-item-theta",
    description: "100% organic and sustainably sourced. This product is certified and meets the highest standards of quality and environmental responsibility.",
    category: "category-4",
    filter_field: "Option E",
    images: ["/images/products/product-8.jpg"],
    retail_price: 54.99,
    wholesale_price: 39.99,
    stock_status: "OUT_OF_STOCK",
    options: ["Small", "Medium"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_009",
    name: "Reserve Item Iota",
    slug: "reserve-item-iota",
    description: "Limited edition reserve item. Once it's gone, it's gone. Premium quality with exclusive finishing touches.",
    category: "category-1",
    filter_field: "Option C",
    images: ["/images/products/product-9.jpg"],
    retail_price: 74.99,
    wholesale_price: 54.99,
    stock_status: "LOW_STOCK",
    options: ["Standard", "Premium"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_010",
    name: "Select Item Kappa",
    slug: "select-item-kappa",
    description: "Hand-selected for quality, this product is part of our premium Select range. Every item passes a rigorous quality control process.",
    category: "category-2",
    filter_field: "Option B",
    images: ["/images/products/product-10.jpg"],
    retail_price: 24.99,
    wholesale_price: 16.99,
    stock_status: "IN_STOCK",
    options: ["Small", "Large"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_011",
    name: "Craft Item Lambda",
    slug: "craft-item-lambda",
    description: "Small-batch crafted with passion. This product features a unique blend of traditional and modern techniques for a distinctive result.",
    category: "category-3",
    filter_field: "Option A",
    images: ["/images/products/product-11.jpg"],
    retail_price: 32.99,
    wholesale_price: 22.99,
    stock_status: "IN_STOCK",
    options: ["Standard", "Large", "Family"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod_012",
    name: "Prime Item Mu",
    slug: "prime-item-mu",
    description: "Our prime selection represents the absolute best we have to offer. Reserved for those who accept nothing but the best quality.",
    category: "category-4",
    filter_field: "Option D",
    images: ["/images/products/product-12.jpg"],
    retail_price: 89.99,
    wholesale_price: 64.99,
    stock_status: "IN_STOCK",
    options: ["Small", "Medium", "Large", "XL"],
    is_archived: false,
    is_featured: false,
    option_configs: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
